name: givenget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  flutter_launcher_icons: ^0.14.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/givenget-logo.png"
  adaptive_icon_foreground: "assets/images/givenget-logo.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
